version: '3.7'

services:
  inji-verify-ui:
    container_name: inji-verify-ui
#    image: kiruthikavjshankar/inji-verify-ui:mosip-connect
    image: inji-verify-ui:local
    pull_policy: never
    ports:
      - "3002:3000"
    environment:
      - INTERNET_CONNECTIVITY_CHECK_ENDPOINT=${INTERNET_CONNECTIVITY_CHECK_ENDPOINT-https://dns.google/}
      - INTERNET_CONNECTIVITY_CHECK_TIMEOUT=${INTERNET_CONNECTIVITY_CHECK_TIMEOUT-10000}
      - OVP_QR_HEADER={OVP_QR_HEADER-INJI_OVP://payload=}
#    platform: linux/amd64
    platform: linux/arm64/v8
#
#
  inji-verify-be:
    container_name: inji-verify-backend
    image:  kiruthikavjshankar/inji-verify-backend:mosip-connect
    pull_policy: never
    ports:
      - "8080:8080"
    platform: linux/arm64/v8

# composable FE
  composable-banking-frontend:
    container_name: composable-banking-frontend
    image: kiruthikavjshankar/composable-banking-client:mosip-connect
    ports:
      - "3000:3000"
    networks:
      - react
    platform: linux/arm64/v8
#
  composable-banking-mock-server:
    container_name: composable-banking-mockserver
    image: kiruthikavjshankar/composable-banking-mock-server:mosip-connect
    ports:
      - "7001:5001"
    networks:
      - react
    platform: linux/arm64/v8

##  composable banking backend
  composable-banking-be-postgres:
    image: postgres
    container_name: composable-banking-be-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cb-user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: onboarding-microservice
    platform: linux/arm64/v8

  composable-banking-be-mountebank:
    image: bbyars/mountebank:2.8.1
    container_name: composable-banking-be-mountebank
    restart: unless-stopped
    command: start
    ports:
      - "2525:2525"
      - "4545:4545"
    platform: linux/arm64/v8

#  composable banking integration layer
  composable-banking-il:
    image: kiruthikavjshankar/composable-banking-il:mosip-connect
    container_name: composable-banking-il
    ports:
      - "8081:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/config/application.properties  # Set properties file path
    volumes:
        - ./config/il-application.properties:/config/application.properties
    platform: linux/arm64/v8

##mobility sample
  mobility-sample-fe:
    container_name: mobility-sample-frontend
    image: kiruthikavjshankar/mobility-sample-fe:mosip-connect
    ports:
      - "3001:3000"
    platform: linux/arm64/v8

  mobility-sample-bap:
    container_name: mobility-sample-bap
    image: kiruthikavjshankar/mobility-sample-bap:mosip-connect
    ports:
      - "2010:2010"
    platform: linux/arm64/v8

#This failing - Error: invalid input
  mobility-sample-bpp:
    container_name: mobility-sample-bpp
    image: kiruthikavjshankar/mobility-sample-bpp:mosip-connect
    ports:
      - "3010:3010"
    platform: linux/arm64/v8

  sample-gateway-registry:
    container_name: sample-gateway-registry
    image: kiruthikavjshankar/sample-gateway-registry:mosip-connect
    ports:
      - "1010:1010"
    platform: linux/arm64/v8

## consent manager
  consent-manager-be:
    container_name: kiruthikavjshankar/consent-manager-be:mosip-connect
    image: kiruthikavjshankar/consent-manager-be:mosip-connect
    ports:
      - "4444:4444"
    platform: linux/arm64/v8

  consent-manager-fe:
    container_name: kiruthikavjshankar/consent-manager-fe:mosip-connect
    image: consent-manager-fe:local
    ports:
      - "3003:3000"
    platform: linux/arm64/v8
networks:
  react:
    driver: bridge